# Generated by Django 2.0.2 on 2019-04-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('transmision', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
            ],
        ),
    ]
