# Generated by Django 2.0.2 on 2019-04-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autos',
            new_name='Auto',
        ),
    ]
